#! /usr/bin/env python3
SSR_RB_TYPE     = 0x53535201 # "SSR" + version 1
SSR_RB_VERSION  = 0x00000100 # version 1.0.
SSR_RB_FEATURES = 0x0000000f

# register block offsets
RBB_COMMON          = 0x00000000
RBB_PROPOSAL_DMA    = 0x00001000
RBB_COMMIT_QUEUE    = 0x00002000
RBB_CONSENSUS       = 0x00003000

# Basic common
COMMON_REG_TYPE             = 0x000
COMMON_REG_VERSION          = 0x004
COMMON_REG_NEXT_PTR         = 0x008
COMMON_REG_FEATURES         = 0x00C
COMMON_REG_CTRL             = 0x010
COMMON_REG_STATUS           = 0x014
COMMON_REG_ERROR            = 0x018
COMMON_REG_SCRATCH          = 0x01C

COMMON_REG_CONFIG_REPLICA_ID    = 0x020
COMMON_REG_CONFIG_REPLICA_NUM   = 0x024
COMMON_REG_CONFIG_ROUND_LEN_NS  = 0x028
COMMON_REG_CONFIG_ETH_TYPE      = 0x02C

COMMON_REG_CONFIG_MACTABLE_ADDR_LO   = 0x100
COMMON_REG_CONFIG_MACTABLE_ADDR_HI   = 0x104

COMMON_REG_PROPOSAL_SINK_CONTROL        = 0x200
COMMON_REG_PROPOSAL_SINK_SLOT_COUNT     = 0x204
COMMON_REG_PROPOSAL_SINK_BEAT_COUNT     = 0x208
COMMON_REG_PROPOSAL_SINK_ERROR_COUNT    = 0x20C

COMMON_REG_COMMIT_GEN_COUNT        = 0x210
COMMON_REG_COMMIT_GEN_CONTROL      = 0x214
COMMON_REG_COMMIT_GEN_STATUS       = 0x218
COMMON_REG_COMMIT_GEN_GENERATED_SLOT_COUNT   = 0x21C
COMMON_REG_COMMIT_GEN_GENERATED_BEAT_COUNT   = 0x220

# PROPOSAL DMA
PROP_DMA_MAGIC          = 0x70726f70 # "prop"
PROP_DMA_VERSION        = 0x00000100 # version 1.0
PROP_DMA_FEATURES       = 0x00000001 # bit 0: support for basic DMA proposal functionality

PROP_DMA_REG_MAGIC              = RBB_PROPOSAL_DMA + 0x000
PROP_DMA_REG_VERSION            = RBB_PROPOSAL_DMA + 0x004
PROP_DMA_REG_FEATURES           = RBB_PROPOSAL_DMA + 0x008
PROP_DMA_REG_CTRL               = RBB_PROPOSAL_DMA + 0x00C
PROP_DMA_REG_STATUS             = RBB_PROPOSAL_DMA + 0x010
PROP_DMA_REG_SCRATCH            = RBB_PROPOSAL_DMA + 0x014
PROP_DMA_REG_ENTRY_COUNTER      = RBB_PROPOSAL_DMA + 0x018

PROP_DMA_REG_ADDR_LO            = RBB_PROPOSAL_DMA + 0x100
PROP_DMA_REG_ADDR_HI            = RBB_PROPOSAL_DMA + 0x104
PROP_DMA_REG_LEN                = RBB_PROPOSAL_DMA + 0x108
PROP_DMA_REG_STRIDE_LO          = RBB_PROPOSAL_DMA + 0x10C
PROP_DMA_REG_STRIDE_HI          = RBB_PROPOSAL_DMA + 0x110
PROP_DMA_REG_COUNT              = RBB_PROPOSAL_DMA + 0x114
PROP_DMA_REG_CONTROL            = RBB_PROPOSAL_DMA + 0x118
PROP_DMA_REG_STATUS             = RBB_PROPOSAL_DMA + 0x11C
PROP_DMA_REG_ACTIVE_INDEX       = RBB_PROPOSAL_DMA + 0x120

# DMA commit queue
COMMIT_DMA_MAGIC       = 0x636f6d71 # "comq"
COMMIT_DMA_VERSION     = 0x00000100 # version 1.0
COMMIT_DMA_FEATURES    = 0x00000001 # bit 0: support for basic DMA commit queue functionality
COMMIT_DMA_CTRL        = 0x00000000
COMMIT_DMA_STATUS      = 0x00000001

COMMIT_DMA_REG_MAGIC              = RBB_COMMIT_QUEUE + 0x000
COMMIT_DMA_REG_VERSION            = RBB_COMMIT_QUEUE + 0x004
COMMIT_DMA_REG_FEATURES           = RBB_COMMIT_QUEUE + 0x008
COMMIT_DMA_REG_CONTROL            = RBB_COMMIT_QUEUE + 0x00C
COMMIT_DMA_REG_STATUS             = RBB_COMMIT_QUEUE + 0x010
COMMIT_DMA_REG_STRIDE_LO          = RBB_COMMIT_QUEUE + 0x014
COMMIT_DMA_REG_STRIDE_HI          = RBB_COMMIT_QUEUE + 0x018
COMMIT_DMA_REG_ACTIVE_BUFFER      = RBB_COMMIT_QUEUE + 0x01C

COMMIT_DMA_REG_BUF0_ADDR_LO       = RBB_COMMIT_QUEUE + 0x100
COMMIT_DMA_REG_BUF0_ADDR_HI       = RBB_COMMIT_QUEUE + 0x104
COMMIT_DMA_REG_BUF0_SLOT_CAPACITY = RBB_COMMIT_QUEUE + 0x108
COMMIT_DMA_REG_BUF0_CONTROL       = RBB_COMMIT_QUEUE + 0x10C
COMMIT_DMA_REG_BUF0_STATUS        = RBB_COMMIT_QUEUE + 0x110
COMMIT_DMA_REG_BUF0_COMPLETED_COUNT = RBB_COMMIT_QUEUE + 0x114
COMMIT_DMA_REG_BUF0_ERROR_COUNT     = RBB_COMMIT_QUEUE + 0x118

COMMIT_DMA_REG_BUF1_ADDR_LO       = RBB_COMMIT_QUEUE + 0x200
COMMIT_DMA_REG_BUF1_ADDR_HI       = RBB_COMMIT_QUEUE + 0x204
COMMIT_DMA_REG_BUF1_SLOT_CAPACITY = RBB_COMMIT_QUEUE + 0x208
COMMIT_DMA_REG_BUF1_CONTROL       = RBB_COMMIT_QUEUE + 0x20C
COMMIT_DMA_REG_BUF1_STATUS        = RBB_COMMIT_QUEUE + 0x210
COMMIT_DMA_REG_BUF1_COMPLETED_COUNT = RBB_COMMIT_QUEUE + 0x214
COMMIT_DMA_REG_BUF1_ERROR_COUNT     = RBB_COMMIT_QUEUE + 0x218   

# Consensus
CONSENSUS_REG_HALT = RBB_CONSENSUS + 0x000
CONSENSUS_REG_GLOBAL_ENABLE = RBB_CONSENSUS + 0x004
CONSENSUS_REG_CTRL_RUN_ID = RBB_CONSENSUS + 0x008
CONSENSUS_REG_CTRL_MEMBERSHIP = RBB_CONSENSUS + 0x00C
CONSENSUS_REG_CTRL_ACTIVATE = RBB_CONSENSUS + 0x010
CONSENSUS_REG_CTRL_REBOOT = RBB_CONSENSUS + 0x014


